### ISSUE TITLE
dp is not defined

### ISSUE THREAD

**Issue by jsalvatier** [agentmodels/webppl-gridworld#13]
When I try to run anything in the browser now I get 'dp is not defined'. 

Any idea what might be going on?

**Comment by stuhlmueller** [comment]
Daniel and I just looked into the same issue in the command line setting. There, the issue was that we called

```
webppl file.wppl --require . --require ../webppl-dp --require ../webppl-timeit
```

instead of 

```
webppl file.wppl --require ../webppl-dp --require ../webppl-timeit --require .
```

That is, `webppl-dp` needed to come before `webppl-gridworld` in the list of dependencies, since the latter depends on the former.

Check the order in which you list the dependencies when you compile for the browser?

**Comment by jsalvatier** [comment]
This did turn out to be the issue. :)
